# Generated by Django 3.1.4 on 2021-09-03 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dipl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='coins',
        ),
    ]
