# Generated by Django 3.1.4 on 2021-06-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default='Surname', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(default='Wallet address', max_length=255),
        ),
    ]
