# Generated by Django 3.1.4 on 2021-09-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipl', '0002_remove_user_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
