# Generated by Django 3.1.4 on 2021-07-23 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipl', '0005_fight_redcornerfighter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='redCornerFighter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dipl.fighter'),
        ),
    ]
