# Generated by Django 3.1.4 on 2021-07-23 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipl', '0006_auto_20210723_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='blueCornerFighter',
            field=models.ForeignKey(blank=True, db_column='blueCornerFighter', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blueCornerFighter', to='dipl.fighter'),
        ),
        migrations.AlterField(
            model_name='fight',
            name='redCornerFighter',
            field=models.ForeignKey(blank=True, db_column='redCornerFighter', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redCornerFighter', to='dipl.fighter'),
        ),
    ]
