# Generated by Django 3.1.4 on 2021-07-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipl', '0007_auto_20210723_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='scheduledFight',
            field=models.BooleanField(default=False),
        ),
    ]
