# Generated by Django 3.1.4 on 2021-07-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipl', '0008_fight_scheduledfight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fight',
            name='scheduledFight',
        ),
        migrations.AddField(
            model_name='fighter',
            name='scheduledFight',
            field=models.BooleanField(default=False),
        ),
    ]
