# Generated by Django 3.1.4 on 2021-07-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipl', '0009_auto_20210723_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
