# Generated by Django 3.1.4 on 2021-07-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipl', '0010_fight_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='redCornerOdds',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fight',
            name='winner_id',
            field=models.IntegerField(null=True),
        ),
    ]
