# Generated by Django 3.1.4 on 2021-07-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipl', '0012_auto_20210724_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='losses',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='reach',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='surname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='wins',
            field=models.IntegerField(null=True),
        ),
    ]
