# Generated by Django 3.1.4 on 2021-07-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipl', '0013_auto_20210725_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='scheduledFight',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
