# Generated by Django 3.1.4 on 2021-07-25 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dipl', '0014_auto_20210725_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='age',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='height',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='reach',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='wins',
        ),
    ]
