# Generated by Django 3.1.4 on 2021-07-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipl', '0015_auto_20210725_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='surname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
