# Generated by Django 3.1.4 on 2021-07-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipl', '0016_fighter_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='wins',
            field=models.IntegerField(null=True),
        ),
    ]
