# Generated by Django 3.1.4 on 2021-07-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipl', '0017_fighter_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='losses',
            field=models.IntegerField(null=True),
        ),
    ]
