# Generated by Django 3.1.4 on 2021-07-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipl', '0019_auto_20210725_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
