# Generated by Django 3.1.4 on 2021-07-26 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dipl', '0022_fighter_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='image',
        ),
    ]
