# Generated by Django 3.1.4 on 2021-07-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipl', '0023_remove_fighter_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
