# Generated by Django 3.1.4 on 2021-07-27 08:25

import dipl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipl', '0024_fighter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=dipl.models.upload_path),
        ),
    ]
