# Generated by Django 3.1.4 on 2021-07-27 21:28

import dipl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipl', '0026_remove_fighter_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=dipl.models.upload_path),
        ),
    ]
