# Generated by Django 3.1.4 on 2021-08-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipl', '0027_fighter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
