# Generated by Django 3.1.4 on 2021-08-04 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipl', '0028_auto_20210802_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fights',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dipl.fight'),
        ),
    ]
