# Generated by Django 3.1.4 on 2021-08-04 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipl', '0029_event_fights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='fights',
        ),
        migrations.AddField(
            model_name='fight',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dipl.event'),
        ),
    ]
