# Generated by Django 3.1.4 on 2021-08-09 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipl', '0034_auto_20210809_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='fight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipl.fight'),
        ),
    ]
