# Generated by Django 3.1.4 on 2021-08-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dipl', '0035_auto_20210809_1923'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bet',
        ),
    ]
