# Generated by Django 3.1.4 on 2021-08-09 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dipl', '0036_delete_bet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_winner', models.IntegerField()),
                ('stake', models.FloatField()),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dipl.fight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
