# Generated by Django 3.1.4 on 2021-08-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipl', '0037_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='success',
            field=models.CharField(default='upcoming', max_length=255),
        ),
    ]
