# Generated by Django 3.1.4 on 2021-08-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipl', '0038_bet_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
