# Generated by Django 3.1.4 on 2021-08-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipl', '0039_auto_20210813_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(default='Wallet address', max_length=255),
        ),
    ]
